// Contract test for the server-sent-events parser in src/services/api.ts.
//
// The fixture is generated by the backend's own framing function
// (backend/scripts/dump_sse_fixture.py), so this checks the client against the
// real wire format rather than an assumption about it. The parser is fed the
// same bytes at many chunk sizes because a network read can land anywhere:
// mid-frame, mid-line, or mid multi-byte character.
//
// Run: npm run test:sse   (no test framework; plain node)
import { execFileSync } from 'child_process';
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const out = mkdtempSync(join(tmpdir(), 'ssetest-'));

// Compile the client to plain JS, then stub the Vite-only env access so node can load it.
// tsc exits non-zero here because `import.meta.env` is a Vite ambient type that this
// standalone invocation does not load; it still emits the JS, which is all we need.
// (`npm run build` is the real type gate for this file.)
const compiled = join(out, 'services', 'api.js');
try {
  execFileSync('npx', ['tsc', 'src/services/api.ts', '--outDir', out, '--module', 'esnext',
    '--target', 'es2022', '--moduleResolution', 'bundler', '--skipLibCheck'],
    { cwd: root, stdio: ['ignore', 'ignore', 'ignore'] });
} catch {
  // fall through to the existence check below
}
if (!existsSync(compiled)) {
  console.error('FAIL: tsc did not emit', compiled);
  process.exit(1);
}
writeFileSync(compiled, readFileSync(compiled, 'utf8')
  .replace(/import\.meta\.env\.VITE_API_URL/g, 'globalThis.__VITE_API_URL'));

const { SSEParser } = await import(`file://${compiled}`);
const fixture = readFileSync(join(here, 'sse_fixture.txt'), 'utf8');

let failures = 0;
const check = (name, cond, extra = '') => {
  if (cond) console.log(`  ok   ${name}`);
  else { console.log(`  FAIL ${name} ${extra}`); failures++; }
};
const EXPECTED = 'Rubisco fixes CO2 onto RuBP in the stroma [1].Multi\nline and "quoted" and émoji 🐵 text';

for (const size of [1, 3, 7, 64, 500, fixture.length]) {
  const events = [];
  const p = new SSEParser(e => events.push(e));
  for (let i = 0; i < fixture.length; i += size) p.push(fixture.slice(i, i + size));
  p.flush();
  const names = events.map(e => e.event).join(',');
  check(`chunk ${size}: event order`, names === 'sources,token,token,token,token,done', names);
  const text = events.filter(e => e.event === 'token').map(e => e.data.text).join('');
  check(`chunk ${size}: token text intact`, text === EXPECTED, JSON.stringify(text));
  const done = events.at(-1)?.data;
  check(`chunk ${size}: citations and query id parsed`,
    done?.citations?.length === 1 && done.citations[0].note_title === 'Photosynthesis' && done.query_id === 41);
  const src = events[0]?.data;
  check(`chunk ${size}: sources event fields`,
    src?.sources?.length === 1 && src.top_score === 0.71 && src.gate_triggered === false);
}
{ // A stream cut short still surfaces its last frame instead of dropping it.
  const events = [];
  const p = new SSEParser(e => events.push(e));
  p.push(fixture.slice(0, fixture.lastIndexOf('\n\n')));
  p.flush();
  check('truncated stream still yields the last frame', events.at(-1)?.event === 'done',
    events.map(e => e.event).join(','));
}
{ // One unparseable frame must not kill the rest of the stream.
  const events = [];
  const p = new SSEParser(e => events.push(e));
  p.push('event: token\ndata: {broken json\n\n');
  p.push('event: token\ndata: {"text":"after"}\n\n');
  p.flush();
  check('malformed frame skipped, stream continues', events.length === 1 && events[0].data.text === 'after');
}
{ // SSE comments (keepalives) carry no event line.
  const events = [];
  const p = new SSEParser(e => events.push(e));
  p.push(': keepalive\n\nevent: token\ndata: {"text":"x"}\n\n');
  p.flush();
  check('keepalive comment ignored', events.length === 1 && events[0].data.text === 'x');
}
console.log(failures === 0 ? '\nSSE parser: all checks passed' : `\nSSE parser: ${failures} FAILURES`);
process.exit(failures ? 1 : 0);
